# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jkv.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'jkv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjkv.proto\">\n\x0fKeyValueVersion\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\"*\n\nKeyVersion\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\".\n\x0cValueVersion\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\"\x88\x02\n\x07Request\x12!\n\x07reqtype\x18\x01 \x01(\x0e\x32\x10.Request.ReqType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x1e\n\x07payload\x18\x03 \x01(\x0b\x32\r.ValueVersion\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x1d\n\x08read_set\x18\x05 \x03(\x0b\x32\x0b.KeyVersion\x12#\n\twrite_set\x18\x06 \x03(\x0b\x32\x10.KeyValueVersion\"V\n\x07ReqType\x12\x08\n\x04PING\x10\x00\x12\x07\n\x03PUT\x10\x01\x12\x07\n\x03GET\x10\x02\x12\x08\n\x04\x46UNC\x10\x03\x12\x0c\n\x08VALIDATE\x10\x04\x12\x0c\n\x08\x42\x45GIN_TX\x10\x05\x12\t\n\x05\x43LEAR\x10\x06\"\xe2\x01\n\x08Response\x12$\n\x08resptype\x18\x01 \x01(\x0e\x32\x12.Response.RespType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x1e\n\x07payload\x18\x03 \x01(\x0b\x32\r.ValueVersion\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\n\n\x02ok\x18\x05 \x01(\x08\x12$\n\nupdate_set\x18\x06 \x03(\x0b\x32\x10.KeyValueVersion\">\n\x08RespType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03GET\x10\x01\x12\x07\n\x03PUT\x10\x02\x12\x08\n\x04\x46UNC\x10\x03\x12\x0c\n\x08VALIDATE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jkv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUEVERSION']._serialized_start=13
  _globals['_KEYVALUEVERSION']._serialized_end=75
  _globals['_KEYVERSION']._serialized_start=77
  _globals['_KEYVERSION']._serialized_end=119
  _globals['_VALUEVERSION']._serialized_start=121
  _globals['_VALUEVERSION']._serialized_end=167
  _globals['_REQUEST']._serialized_start=170
  _globals['_REQUEST']._serialized_end=434
  _globals['_REQUEST_REQTYPE']._serialized_start=348
  _globals['_REQUEST_REQTYPE']._serialized_end=434
  _globals['_RESPONSE']._serialized_start=437
  _globals['_RESPONSE']._serialized_end=663
  _globals['_RESPONSE_RESPTYPE']._serialized_start=601
  _globals['_RESPONSE_RESPTYPE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
